#!/usr/bin/env bash
set -e

IMAGE_NAME="squirrel-server-s3"
IMAGE_NAME_BASE="${IMAGE_NAME}--base"
IMAGE_NAME_TEST="${IMAGE_NAME}--test"

docker build --tag $IMAGE_NAME_BASE --file Dockerfile .
docker build --tag $IMAGE_NAME_TEST --file Dockerfile.test .

docker run --rm --volume "$PWD":/app $IMAGE_NAME_TEST ./script/lint
docker run --rm --volume "$PWD":/app $IMAGE_NAME_TEST ./script/compile
docker run --rm --volume "$PWD":/app $IMAGE_NAME_TEST ./script/test

docker tag $IMAGE_NAME_BASE $IMAGE_NAME
